# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.44.1"

default_platform :ios

lane :beta do |values|
  # Fabric generated this lane for deployment to Crashlytics Beta
  # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
  gym(scheme: 'Pillowz', export_method: 'ad-hoc')

  emails = values[:test_email] ? values[:test_email] : ['s.bukenov@gmail.com', 'koshkarov@gmail.com'] # You can list more emails here
  groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
  #

  crashlytics(api_token: '6bdcb7eb1f7189d6e532de77990bc02ffc048ffb',
           build_secret: '5bb764dc6551d829772d5a762006f7f12b2e44f4dc1a3d98be2b36a372e4c2f9',
                 emails: emails,
                 groups: groups,
                  notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
          notifications: true) # Should this distribution notify your testers via email?

  # for all available options run `fastlane action crashlytics`

  # You can notify your team in chat that a beta build has been uploaded
  # slack(
  #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
  #   channel: "beta-releases",
  #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
  # )
end


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "kaz.innovatech.Pillowz") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "kaz.innovatech.Pillowz") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
